bedroom_choices = {
  '1':1,
  '2':2,
  '3':3,
  '4':4,
  '5':5,
  '6':6,
  '7':7,
  '8':8,
  '9':9,
  '10':10
  }

price_choices = {
  '5000':'Rs 5000',
  '10000':'Rs 10,000',
  '20000':'Rs 20,000',
  '50000':'Rs 50,000',
  '100000':'Rs 1,00,000',
  '200000':'Rs 2,00,000',
  '500000':'Rs 5,00,000',
  '700000':'Rs 7,00,000',
  '1000000':'Rs 10,00,000',
}

state_choices = {
        'AN': 'Andaman and Nicobar Islands',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}

state_choices = {
                  'AN'	:	'Andaman and Nicobar Islands',
                  'AP'	:	'Andhra Pradesh',
                  'AR'	:	'Arunachal Pradesh',
                  'AS'	:	'Assam',
                  'BR'	:	'Bihar',
                  'CH'	:	'Chandigarh',
                  'CT'	:	'Chhattisgarh',
                  'DN'	:	'Dadra and Nagar Haveli',
                  'DD'	:	'Daman and Diu',
                  'DL'	:	'Delhi',
                  'GA'	:	'Goa',
                  'GJ'	:	'Gujarat',
                  'HR'	:	'Haryana',
                  'HP'	:	'Himachal Pradesh',
                  'JK'	:	'Jammu and Kashmir',
                  'JH'	:	'Jharkhand',
                  'KA'	:	'Karnataka',
                  'KL'	:	'Kerala',
                  'LD'	:	'Lakshadweep',
                  'MP'	:	'Madhya Pradesh',
                  'MH'	:	'Maharashtra',
                  'MN'	:	'Manipur',
                  'ML'	:	'Meghalaya',
                  'MZ'	:	'Mizoram',
                  'NL'	:	'Nagaland',
                  'OR'	:	'Odisha',
                  'PY'	:	'Puducherry',
                  'PB'	:	'Punjab',
                  'RJ'	:	'Rajasthan',
                  'SK'	:	'Sikkim',
                  'TN'	:	'Tamil Nadu',
                  'TG'	:	'Telangana',
                  'TR'	:	'Tripura',
                  'UP'	:	'Uttar Pradesh',
                  'UT'	:	'Uttarakhand',
                  'WB'	:	'West Bengal'

}